model Cardiovascular.Examples.DizertaceExample.HydraulicElastance
parameter Real V0;
parameter Real p0;
parameter Real C;

Real V;
Real qin.q;
Real qin.p;

// Equations and algorithms

  // Component 
  // class Cardiovascular.Examples.DizertaceExample.HydraulicElastance
  equation
    qin.p-p0 = (if V < V0 then 0 else (V-V0)/C);
    qin.q = der(V);
    qin.q = 0.0;

end Cardiovascular.Examples.DizertaceExample.HydraulicElastance;
